In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
from sklearn import preprocessing


C:\Users\Dhanush Kumar R\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\Dhanush Kumar R\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
C:\Users\Dhanush Kumar R\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [2]:
raw_csv_data = np.loadtxt('Audiobooks_data.csv', delimiter = ',')

In [3]:
unscaled_inputs_all = raw_csv_data[:,1:-1]


In [4]:
target_all = raw_csv_data[:,-1]

In [5]:
raw_csv_data

array([[8.7300e+02, 2.1600e+03, 2.1600e+03, ..., 0.0000e+00, 0.0000e+00,
        1.0000e+00],
       [6.1100e+02, 1.4040e+03, 2.8080e+03, ..., 0.0000e+00, 1.8200e+02,
        1.0000e+00],
       [7.0500e+02, 3.2400e+02, 3.2400e+02, ..., 1.0000e+00, 3.3400e+02,
        1.0000e+00],
       ...,
       [2.8671e+04, 1.0800e+03, 1.0800e+03, ..., 0.0000e+00, 2.9000e+01,
        0.0000e+00],
       [3.1134e+04, 2.1600e+03, 2.1600e+03, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [3.2832e+04, 1.6200e+03, 1.6200e+03, ..., 0.0000e+00, 9.0000e+01,
        0.0000e+00]])

In [6]:
target_all

array([1., 1., 1., ..., 0., 0., 0.])

In [7]:
unscaled_inputs_all

array([[2.160e+03, 2.160e+03, 1.013e+01, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [1.404e+03, 2.808e+03, 6.660e+00, ..., 0.000e+00, 0.000e+00,
        1.820e+02],
       [3.240e+02, 3.240e+02, 1.013e+01, ..., 0.000e+00, 1.000e+00,
        3.340e+02],
       ...,
       [1.080e+03, 1.080e+03, 6.550e+00, ..., 0.000e+00, 0.000e+00,
        2.900e+01],
       [2.160e+03, 2.160e+03, 6.140e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [1.620e+03, 1.620e+03, 5.330e+00, ..., 0.000e+00, 0.000e+00,
        9.000e+01]])

Balance the dataset

In [8]:
num_one_targets = int(np.sum(target_all))
zero_targets_counter = 0
indices_to_remove = []

for i in range(target_all.shape[0]):
    if target_all[i] == 0:
        zero_targets_counter +=1
        if zero_targets_counter> num_one_targets :
            indices_to_remove.append(i)
unscaled_inputs_equal_priors = np.delete(unscaled_inputs_all,indices_to_remove,axis=0)
targets_equal_priors = np.delete(target_all,indices_to_remove,axis = 0)

In [26]:
num_one_targets
len(indices_to_remove)

9610

standaridze the inputs

In [9]:
scaled_inputs= preprocessing.scale(unscaled_inputs_equal_priors)

In [10]:
scaled_inputs

array([[ 1.18956512,  0.36398846,  0.67728889, ..., -0.8635056 ,
        -0.20536617, -0.77240946],
       [-0.33022754,  1.10843845, -0.08841391, ..., -0.8635056 ,
        -0.20536617,  1.16499791],
       [-2.50135991, -1.74528653,  0.67728889, ..., -0.8635056 ,
         2.23179102,  2.78305242],
       ...,
       [ 1.18956512,  0.36398846,  0.67728889, ..., -0.20129479,
        -0.20536617, -0.62337812],
       [ 1.18956512,  0.36398846,  0.27347444, ..., -0.20129479,
        -0.20536617,  0.21758442],
       [ 1.18956512,  0.36398846,  0.20727535, ..., -0.20129479,
        -0.20536617, -0.51692717]])

shuffle the data

In [14]:
shuffled_indices = np.arange(scaled_inputs.shape[0])
np.random.shuffle(shuffled_indices)

shuffled_inputs = scaled_inputs[shuffled_indices]
shuffled_targets = targets_equal_priors[shuffled_indices]

In [15]:
shuffled_indices

array([2330,  384, 4095, ..., 1346, 3411, 3142])

In [16]:
shuffled_inputs

array([[ 1.18956512,  0.36398846, -0.14578645, ..., -0.8635056 ,
        -0.20536617, -0.77240946],
       [ 0.10399894, -0.25638654, -0.26273818, ...,  0.18499485,
        -0.20536617,  0.01532761],
       [-0.76445401, -0.75268653, -0.38189654, ...,  0.35054755,
        -0.20536617, -0.58079774],
       ...,
       [-0.76445401, -0.75268653, -0.02883473, ..., -0.8635056 ,
        -0.20536617, -0.77240946],
       [ 0.10399894, -0.25638654,  1.85563267, ...,  0.87479777,
        -0.20536617,  1.75047816],
       [-0.76445401, -0.75268653, -0.02883473, ...,  0.91618595,
        -0.20536617,  1.4417704 ]])

In [17]:
shuffled_targets

array([0., 1., 0., ..., 1., 0., 0.])

split the data into train,validation,test

In [18]:
samples_count = shuffled_inputs.shape[0]

train_samples_count = int(0.8*samples_count)
validation_samples_count = int(0.1*samples_count)
test_samples_count = train_samples_count - validation_samples_count

print("count")
print(samples_count)
print(train_samples_count)
print(validation_samples_count)
print(test_samples_count)

count
4474
3579
447
3132


In [19]:
train_inputs = shuffled_inputs[:train_samples_count]
train_targets = shuffled_inputs[:train_samples_count]
validation_inputs = shuffled_inputs[train_samples_count:train_samples_count+validation_samples_count]
validation_targets = shuffled_targets[train_samples_count:train_samples_count+validation_samples_count]

test_inputs = shuffled_inputs[train_samples_count+validation_samples_count:]
test_targets = shuffled_targets[train_samples_count+validation_samples_count:]

In [20]:
print("train data\n")
print(train_inputs)
print(train_targets)
print("validaion data\n")
print(validation_inputs)
print(validation_targets)
print("test data")
print(test_inputs)
print(test_targets)

train data

[[ 1.18956512  0.36398846 -0.14578645 ... -0.8635056  -0.20536617
  -0.77240946]
 [ 0.10399894 -0.25638654 -0.26273818 ...  0.18499485 -0.20536617
   0.01532761]
 [-0.76445401 -0.75268653 -0.38189654 ...  0.35054755 -0.20536617
  -0.58079774]
 ...
 [-2.50135991 -1.74528653 -0.20536563 ... -0.8635056  -0.20536617
  -0.77240946]
 [ 1.18956512  0.36398846 -0.66655262 ... -0.8635056  -0.20536617
  -0.33596054]
 [ 0.10399894 -0.25638654 -0.38189654 ...  0.18499485 -0.20536617
  -0.77240946]]
[[ 1.18956512  0.36398846 -0.14578645 ... -0.8635056  -0.20536617
  -0.77240946]
 [ 0.10399894 -0.25638654 -0.26273818 ...  0.18499485 -0.20536617
   0.01532761]
 [-0.76445401 -0.75268653 -0.38189654 ...  0.35054755 -0.20536617
  -0.58079774]
 ...
 [-2.50135991 -1.74528653 -0.20536563 ... -0.8635056  -0.20536617
  -0.77240946]
 [ 1.18956512  0.36398846 -0.66655262 ... -0.8635056  -0.20536617
  -0.33596054]
 [ 0.10399894 -0.25638654 -0.38189654 ...  0.18499485 -0.20536617
  -0.77240946]]
vali

In [21]:
print(np.sum(train_targets),train_samples_count,np.sum(train_targets)/train_samples_count)
print(np.sum(test_targets),test_samples_count,np.sum(test_targets)/test_samples_count)
print(np.sum(validation_targets),validation_samples_count,np.sum(validation_targets)/validation_samples_count)

-25.61684810061702 3579 -0.007157543476003638
220.0 3132 0.070242656449553
230.0 447 0.5145413870246085


save the dataset

In [22]:
np.savez('audiobooks_data_train',inputs = train_inputs,targets = train_targets)
np.savez('audiobooks_data_validations',inputs = validation_inputs,targets =validation_targets)
np.savez('audiobooks_data_test',inputs = test_inputs,targets = test_targets)

Importing the data

In [28]:
npz = np.load('audiobooks_data_train.npz')

In [29]:
npz

In [33]:
train_inputs = npz['inputs'].astype(np.float32)
train_targets = npz['targets'].astype(np.int64)
npz = np.load('audiobooks_data_validations.npz')
validation_inputs,validation_targets = npz['inputs'].astype(np.float32),npz['targets'].astype(np.int64)
npz = np.load('audiobooks_data_test.npz')
test_inputs,test_targets = npz['inputs'].astype(np.float32),npz['targets'].astype(np.int64)

In [34]:
print(train_inputs)
print(train_targets)
print(validation_inputs,validation_targets)
print(test_inputs,test_targets)


[[ 1.1895651   0.36398846 -0.38189653 ...  0.916186    2.231791
   0.5262922 ]
 [ 1.1895651   0.36398846  0.20727536 ... -0.8635056  -0.20536618
  -0.6020879 ]
 [ 0.10399894 -0.25638655  0.20727536 ...  0.35054755 -0.20536618
  -0.6020879 ]
 ...
 [-0.764454   -0.75268656 -0.02883473 ... -0.8635056  -0.20536618
  -0.77240944]
 [ 0.10399894 -0.25638655  1.8556327  ...  0.87479776 -0.20536618
   1.7504781 ]
 [-0.764454   -0.75268656 -0.02883473 ...  0.916186   -0.20536618
   1.4417704 ]]
[1 1 0 0 1 0 0 0 1 1 1 1 0 0 0 0 0 0 1 0 0 1 0 1 0 0 1 0 0 0 0 1 0 1 1 0 1
 1 0 0 1 0 0 1 1 1 1 1 1 1 0 1 1 0 0 0 0 1 1 1 1 1 1 0 0 0 0 1 0 1 1 0 0 1
 0 1 0 1 0 0 1 0 0 0 1 0 1 0 1 1 1 0 0 0 1 0 0 0 0 1 1 0 1 0 1 0 1 1 1 1 1
 1 0 1 1 1 0 1 0 1 1 1 0 1 0 0 0 1 1 0 0 0 1 0 0 1 0 1 0 0 0 1 1 0 1 0 0 1
 1 0 0 1 1 0 0 0 0 0 1 0 1 1 1 1 0 0 1 1 0 0 0 0 0 1 1 0 0 1 0 0 0 1 1 1 0
 1 0 1 0 0 1 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 1 0 1 1 0 1 1 1 0 0 0 0 1 0 0 1 0 0 1 1 1 1

model

In [39]:
input_size = 10
output_size =2 
hidden_layer_size = 50

model = tf.keras.Sequential([
    tf.keras.layers.Dense(hidden_layer_size, activation='relu'),
    tf.keras.layers.Dense(hidden_layer_size, activation = 'relu'),
    tf.keras.layers.Dense(hidden_layer_size,activation = 'softmax')
])

model.compile(optimizer = 'adam',loss = 'sparse_categorical_crossentropy', metrics =['accuracy'])

batch_size =  100
max_epoch = 100
early_stopping = tf.keras.callbacks.EarlyStopping(patience =2)

model.fit(train_inputs,train_targets,batch_size = batch_size,epochs = max_epoch,
          callbacks=[early_stopping],validation_data =(validation_inputs, validation_targets),verbose =2)

Epoch 1/100
5/5 - 1s - loss: 3.9055 - accuracy: 0.0022 - val_loss: 3.7684 - val_accuracy: 0.0872 - 546ms/epoch - 109ms/step
Epoch 2/100
5/5 - 0s - loss: 3.6770 - accuracy: 0.1808 - val_loss: 3.5411 - val_accuracy: 0.3132 - 34ms/epoch - 7ms/step
Epoch 3/100
5/5 - 0s - loss: 3.4482 - accuracy: 0.4286 - val_loss: 3.3090 - val_accuracy: 0.6532 - 34ms/epoch - 7ms/step
Epoch 4/100
5/5 - 0s - loss: 3.2110 - accuracy: 0.7433 - val_loss: 3.0604 - val_accuracy: 0.7740 - 33ms/epoch - 7ms/step
Epoch 5/100
5/5 - 0s - loss: 2.9528 - accuracy: 0.8058 - val_loss: 2.7869 - val_accuracy: 0.7919 - 32ms/epoch - 6ms/step
Epoch 6/100
5/5 - 0s - loss: 2.6706 - accuracy: 0.8304 - val_loss: 2.4868 - val_accuracy: 0.8233 - 35ms/epoch - 7ms/step
Epoch 7/100
5/5 - 0s - loss: 2.3611 - accuracy: 0.8304 - val_loss: 2.1653 - val_accuracy: 0.8300 - 40ms/epoch - 8ms/step
Epoch 8/100
5/5 - 0s - loss: 2.0335 - accuracy: 0.8348 - val_loss: 1.8321 - val_accuracy: 0.8322 - 44ms/epoch - 9ms/step
Epoch 9/100
5/5 - 0s - loss: 

Test the model

In [40]:
test_loss,test_accuracy = model.evaluate(test_inputs, test_targets)

14/14 [==============================] - 0s 1ms/step - loss: 0.2433 - accuracy: 0.9040


In [42]:
print("test loss : {0: .2f}. Test accuracy : {1:2f}%".format(test_loss, test_accuracy*100))

test loss :  0.24. Test accuracy : 90.401787%
